title: "               <black>Ayarlar"
rows: 3
filler-material: "GRAY_STAINED_GLASS_PANE"
filler-slots:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
items:
  back:
    material: "BARRIER"
    model-data: 0
    amount: 1
    display-name: "<#ff0000>Geri Dön"
    glowing: false
    head-data: null
    lore:
      - ""
    slots:
      - 22
    actions:
      - "[menu] manage"
dynamic-items:
  auto-harvest:
    enabled:
      material: "NETHERITE_HOE"
      model-data: 0
      amount: 1
      display-name: "<#11ff00>Otomatik Hasat"
      glowing: false
      head-data: "texture-ewogICJ0aW1lc3RhbXAiIDogMTcyNDM2OTU1Njg1MywKICAicHJvZmlsZUlkIiA6ICIxNWJmNDJhNTU1ZjQ0NGRiODE3NzQwNTc3NDVhZDg3ZCIsCiAgInByb2ZpbGVOYW1lIiA6ICJEZWFuTGUiLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGRjMDAyNjFjYTc2ZmNhNTMzYzhlNzQwNDUyNTVmNDA5MzYxZjE0NWRhMTY3NzFkZjkyMDU1NDIwMzcwOTg5OCIKICAgIH0KICB9Cn0="
      lore:
        - ""
        - " <gray>Bölgenizdeki ekinleri"
        - " <gray>büyüdüklerinde otomatik olarak hasatlar"
        - ""
        - " <gray>Durum: <#11ff00>Etkin"
        - ""
        - "<#ffea00>▶ Değiştirmek için tıklayın!"
      slots:
        - 10
    disabled:
      material: "NETHERITE_HOE"
      model-data: 0
      amount: 1
      display-name: "<#ff0000>Otomatik Hasat"
      glowing: false
      head-data: "texture-ewogICJ0aW1lc3RhbXAiIDogMTcyNDM2OTU1Njg1MywKICAicHJvZmlsZUlkIiA6ICIxNWJmNDJhNTU1ZjQ0NGRiODE3NzQwNTc3NDVhZDg3ZCIsCiAgInByb2ZpbGVOYW1lIiA6ICJEZWFuTGUiLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGRjMDAyNjFjYTc2ZmNhNTMzYzhlNzQwNDUyNTVmNDA5MzYxZjE0NWRhMTY3NzFkZjkyMDU1NDIwMzcwOTg5OCIKICAgIH0KICB9Cn0="
      lore:
        - ""
        - " <gray>Bölgenizdeki ekinleri"
        - " <gray>büyüdüklerinde otomatik olarak hasatlar"
        - ""
        - " <gray>Durum: <#ff0000>Pasif"
        - ""
        - "<#ffea00>▶ Değiştirmek için tıklayın!"
      slots:
        - 10
  auto-kill:
    enabled:
      material: "NETHERITE_SWORD"
      model-data: 0
      amount: 1
      display-name: "<#11ff00>Otomatik Öldürme"
      glowing: false
      head-data: null
      lore:
        - ""
        - " <gray>Bölgenizdeki moblardan"
        - " <gray>türeyen yaratıkları otomatik öldürür"
        - ""
        - " <gray>Durum: <#11ff00>Etkin"
        - ""
        - "<#ffea00>▶ Değiştirmek için tıklayın!"
      slots:
        - 12
    disabled:
      material: "NETHERITE_SWORD"
      model-data: 0
      amount: 1
      display-name: "<#ff0000>Otomatik Öldürme"
      glowing: false
      head-data: null
      lore:
        - ""
        - " <gray>Bölgenizdeki moblardan"
        - " <gray>türeyen yaratıkları otomatik öldürür"
        - ""
        - " <gray>Durum: <#ff0000>Pasif"
        - ""
        - "<#ffea00>▶ Değiştirmek için tıklayın!"
      slots:
        - 12
  auto-sell:
    enabled:
      material: "GOLD_INGOT"
      model-data: 0
      amount: 1
      display-name: "<#11ff00>Otomatik Satış"
      glowing: false
      head-data: null
      lore:
        - ""
        - " <gray>Toplanan ürünleri"
        - " <gray>otomatik olarak satar"
        - ""
        - " <gray>Durum: <#11ff00>Etkin"
        - ""
        - "<#ffea00>▶ Değiştirmek için tıklayın!"
      slots:
        - 14
    disabled:
      material: "GOLD_INGOT"
      model-data: 0
      amount: 1
      display-name: "<#ff0000>Otomatik Satış"
      glowing: false
      head-data: null
      lore:
        - ""
        - " <gray>Toplanan ürünleri"
        - " <gray>otomatik olarak satar"
        - ""
        - " <gray>Durum: <#ff0000>Pasif"
        - ""
        - "<#ffea00>▶ Değiştirmek için tıklayın!"
      slots:
        - 14
  xp-collector:
    enabled:
      material: "PLAYER_HEAD"
      model-data: 0
      amount: 1
      display-name: "<#11ff00>XP Toplayıcı"
      glowing: false
      head-data: "texture-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTI4Mzk2NTkyM2MwZTNlYWQwZmU4NzYwZTA4Y2JhODk4MmUzM2E2YWNkYjg5MWVjYzZmNmRmZTZkNWQxODBiYyJ9fX0="
      lore:
        - ""
        - " <gray>Yere düşen tecrübeleri"
        - " <gray>otomatik olarak toplar"
        - ""
        - " <gray>Durum: <#11ff00>Etkin"
        - ""
        - "<#ffea00>▶ Click to change!"
      slots:
        - 16
    disabled:
      material: "PLAYER_HEAD"
      model-data: 0
      amount: 1
      display-name: "<#ff0000>XP Toplayıcı"
      glowing: false
      head-data: "texture-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTI4Mzk2NTkyM2MwZTNlYWQwZmU4NzYwZTA4Y2JhODk4MmUzM2E2YWNkYjg5MWVjYzZmNmRmZTZkNWQxODBiYyJ9fX0="
      lore:
        - ""
        - " <gray>Yere düşen tecrübeleri"
        - " <gray>otomatik olarak toplar"
        - ""
        - " <gray>Durum: <#ff0000>Pasif"
        - ""
        - "<#ffea00>▶ Click to change!"
      slots:
        - 16